version: "3.8"

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: consultorio_db
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backendconsul:
    build: ./backendConsul
    container_name: backendConsul
    restart: always
    env_file:
      - ./backendConsul/.env.production
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - uploads-data:/app/src/uploads

  consultorio:
    image: nginx:alpine
    container_name: consultorio
    restart: always
    ports:
      - "80:80"
      - "443:443"   # <- habilitamos HTTPS
    volumes:
      - ./consultorio/dist/consultorio/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # <- montamos los certificados
    depends_on:
      - backendconsul
    environment:
      TZ: America/Argentina/Buenos_Aires

volumes:
  db-data:
  uploads-data:
