services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: Manuti12174328
      POSTGRES_PASSWORD: 9cM4U438mq
      POSTGRES_DB: consultorio_db
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - ./db-init/backup_20260104.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backendconsul:
    build: ./backendConsul
    container_name: backendConsul
    restart: always
    env_file:
      - ./backendConsul/.env.production
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/src/uploads

  consultorio:
    image: nginx:alpine
    container_name: consultorio
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./consultorio/dist/consultorio/browser:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backendconsul

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Este comando intenta renovar cada 12 horas autom√°ticamente
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db-data:
